apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: caching-service-ingress
spec:
  rules:
  - host: caching-service.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: caching-service
            port: 
              number: 80