# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  redis:
    image: redis
    ports:
      - 6379:6379

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_SERVER}:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  caching-service:
    image: 'rahul10pu/caching-service'
    ports:
      - '8080:8080'
    environment:
      - MONGODB_SERVER=${MONGODB_SERVER}
      - MONGODB_ADMINUSERNAME=root
      - MONGODB_ADMINPASSWORD=example
      - REDIS_SERVER=${REDIS_SERVER}
      - KAFKA_SERVER=${KAFKA_SERVER}
      - REDIS_PORT=${REDIS_PORT}


volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local